### ISSUE TITLE
Release v0.3.1 to npm (or new minor version)

### ISSUE THREAD

**Issue by mwoc** [One-com/requirejs-tpl#4]
I currently don't have access to npm publish v0.3.1, nor do I know if that's a good idea - maybe we need a minor version bump with the other changes that are currently unreleased? @sunesimonsen

**Comment by sunesimonsen** [comment]
If I'm the owner of the package I'll add a few of the other team members.

**Comment by sunesimonsen** [comment]
@papandreou owns the package

**Comment by papandreou** [comment]
@mwoc Added you as an owner.
